/**:
  ros__parameters:
    weights_path: "/home/sponer/ws_openvins_superpoint/src/superpoint_test_extractor/superpoint_model_weights.bin"
    image_topic: "/camera/image"
    nfeatures: 500
    scale_factor: 1.2
    nlevels: 4
    threshold: 0.015
    min_threshold: 0.007
    do_nms: true
    use_cuda: false
    match_threshold: 0.7
    max_track_length: 5
    min_track_length: 2
    image_size: [320, 180]   # width, height

      
#  threshold: 0.015
# [320, 180] 
# 640 x 360 for my webcam - 16:9
