#superpoint params
weights_path:"/home/sponer/ws_openvins_superpoint/src/mrs_open_vins_superpoint/ov_core/src/track/superpoint_model_weights.bin" #absolute path to cnn weights
do_nms: true 

use_cuda: true #true to use cuda graphical accelaration
sp_threshold: 0.50 #nehraje roli - pouziva nejdriv iniTh a pak minTh
#sp extractor
sp_nfeatures:  1500
sp_scaleFactor: 1.2
sp_nlevels: 1 
sp_iniThFAST: 0.015
sp_minThFAST: 0.007